name: nlp-final
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - ipykernel
  - jupyter
  - requests
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ollama
  - pip
  - pip:
    - sentence-transformers
    - scikit-learn
